In [4]:
from google.colab import files
import pandas as pd
import io
uploaded = files.upload() # opens file picker
df = pd.read_csv(io.BytesIO(uploaded["student_performance.csv"]))
print(df.head())

Saving student_performance.csv to student_performance.csv
  Student_ID              Name  Gender  Age        Department  Attendance  \
0     STU001        Joy Ibekwe    Male   23  Computer Science       100.0
1     STU002    Sarah Olatunji    Male   22    AI Engineering        97.0
2     STU003  Mariam Abdullahi  Female   20      Data Science        94.0
3     STU004       Hannah Uche  Female   24      Data Science        69.0
4     STU005   Daniel Ogunbiyi    Male   22      Data Science        98.0

   Study_Hours  Assignment_Score  Quiz_Score  Exam_Score  Final_Score Pass
0          4.4                45        44.0          42         43.0   No
1          8.5                57        51.0          53         53.4  Yes
2          8.5                71        71.0          61         65.0  Yes
3          5.8                54        49.0          46         48.2   No
4          6.4                48        54.0          55         53.4  Yes

In [6]:
from sklearn.preprocessing import MinMaxScaler

In [8]:
scaler = MinMaxScaler()

df["Atendance_Normalized"] = scaler.fit_transform(df[["Attendance"]])

df.head(20)

,Student_ID,Name,Gender,Age,Department,Attendance,Study_Hours,Assignment_Score,Quiz_Score,Exam_Score,Final_Score,Pass,Atendance_Normalized
0,STU001,Joy Ibekwe,Male,23,Computer Science,100.0,4.4,45,44.0,42,43.0,No,1.000000
1,STU002,Sarah Olatunji,Male,22,AI Engineering,97.0,8.5,57,51.0,53,53.4,Yes,0.960000
2,STU003,Mariam Abdullahi,Female,20,Data Science,94.0,8.5,71,71.0,61,65.0,Yes,0.920000
3,STU004,Hannah Uche,Female,24,Data Science,69.0,5.8,54,49.0,46,48.2,No,0.586667
4,STU005,Daniel Ogunbiyi,Male,22,Data Science,98.0,6.4,48,54.0,55,53.4,Yes,0.973333
5,STU006,Grace Usman,Male,24,Data Science,100.0,30.0,81,79.0,73,75.8,Yes,1.000000
6,STU007,Juliet Ahmed,Female,19,Data Science,65.0,14.1,88,92.0,86,87.6,Yes,0.533333
7,STU008,Daniela Abdullahi,Male,19,Software Engineering,82.0,5.7,51,45.0,60,55.2,Yes,0.760000
8,STU009,Sarah Bello,Female,21,Data Science,84.0,6.5,54,56.0,45,49.0,No,0.786667
9,STU010,Dorcas Ogunlana,Female,19,Data Science,64.0,5.7,53,51.0,63,58.6,Yes,0.520000
10,STU011,James Ogunleye,Male,19,Software Engineering,68.0,6.2,54,59.0,62,59.8,Yes,0.573333
11,STU012,Ruth Kalu,Female,22,Computer Science,65.0,12.8,82,78.0,92,87.2,Yes,0.533333
12,STU013,Benjamin Adeyemi,Male,23,Data Science,84.0,8.0,69,77.0,67,69.4,Yes,0.786667
13,STU014,Amina Alabi,Female,22,AI Engineering,81.0,4.5,50,47.0,54,51.8,Yes,0.746667
14,STU015,Mary Olawale,Female,24,AI Engineering,92.0,14.9,98,100.0,100,99.6,Yes,0.893333
15,STU016,David Nwachukwu,Female,24,Data Science,94.0,15.4,92,94.0,97,95.4,Yes,0.920000
16,STU017,Fatima Osei,Male,19,Software Engineering,75.0,3.8,40,40.0,45,43.0,No,0.666667
17,STU018,Mariam Alabi,Male,23,Data Science,95.0,5.1,53,51.0,60,56.8,Yes,0.933333
18,STU019,Andrew Nwachukwu,Male,19,Computer Science,25.0,15.9,100,100.0,100,100.0,Yes,0.000000
19,STU020,Fatima Ibeh,Male,19,Computer Science,81.0,3.3,40,40.0,40,40.0,No,0.746667

In [9]:
encoded_df = pd.get_dummies(df, columns=["Department"], dtype=int)

encoded_df.head(20)

,Student_ID,Name,Gender,Age,Attendance,Study_Hours,Assignment_Score,Quiz_Score,Exam_Score,Final_Score,Pass,Atendance_Normalized,Department_AI Engineering,Department_Computer Science,Department_Data Science,Department_Software Engineering
0,STU001,Joy Ibekwe,Male,23,100.0,4.4,45,44.0,42,43.0,No,1.000000,0,1,0,0
1,STU002,Sarah Olatunji,Male,22,97.0,8.5,57,51.0,53,53.4,Yes,0.960000,1,0,0,0
2,STU003,Mariam Abdullahi,Female,20,94.0,8.5,71,71.0,61,65.0,Yes,0.920000,0,0,1,0
3,STU004,Hannah Uche,Female,24,69.0,5.8,54,49.0,46,48.2,No,0.586667,0,0,1,0
4,STU005,Daniel Ogunbiyi,Male,22,98.0,6.4,48,54.0,55,53.4,Yes,0.973333,0,0,1,0
5,STU006,Grace Usman,Male,24,100.0,30.0,81,79.0,73,75.8,Yes,1.000000,0,0,1,0
6,STU007,Juliet Ahmed,Female,19,65.0,14.1,88,92.0,86,87.6,Yes,0.533333,0,0,1,0
7,STU008,Daniela Abdullahi,Male,19,82.0,5.7,51,45.0,60,55.2,Yes,0.760000,0,0,0,1
8,STU009,Sarah Bello,Female,21,84.0,6.5,54,56.0,45,49.0,No,0.786667,0,0,1,0
9,STU010,Dorcas Ogunlana,Female,19,64.0,5.7,53,51.0,63,58.6,Yes,0.520000,0,0,1,0
10,STU011,James Ogunleye,Male,19,68.0,6.2,54,59.0,62,59.8,Yes,0.573333,0,0,0,1
11,STU012,Ruth Kalu,Female,22,65.0,12.8,82,78.0,92,87.2,Yes,0.533333,0,1,0,0
12,STU013,Benjamin Adeyemi,Male,23,84.0,8.0,69,77.0,67,69.4,Yes,0.786667,0,0,1,0
13,STU014,Amina Alabi,Female,22,81.0,4.5,50,47.0,54,51.8,Yes,0.746667,1,0,0,0
14,STU015,Mary Olawale,Female,24,92.0,14.9,98,100.0,100,99.6,Yes,0.893333,1,0,0,0
15,STU016,David Nwachukwu,Female,24,94.0,15.4,92,94.0,97,95.4,Yes,0.920000,0,0,1,0
16,STU017,Fatima Osei,Male,19,75.0,3.8,40,40.0,45,43.0,No,0.666667,0,0,0,1
17,STU018,Mariam Alabi,Male,23,95.0,5.1,53,51.0,60,56.8,Yes,0.933333,0,0,1,0
18,STU019,Andrew Nwachukwu,Male,19,25.0,15.9,100,100.0,100,100.0,Yes,0.000000,0,1,0,0
19,STU020,Fatima Ibeh,Male,19,81.0,3.3,40,40.0,40,40.0,No,0.746667,0,1,0,0

In [10]:
df.to_csv("student_performance_cleaned.csv", index=False)
print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.